language: node_js

node_js:
  - "12"
  - "14"
  - "16"
  
script:
  - npm install
  - npm test
  - npm run lint
  - npm run build

after_success:
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN